#![forbid(unsafe_code)]
#![deny(rust_2018_idioms)]

//! Transport-independent contracts for the Rust Factory project brick.
//!
//! The agent-facing MCP surface lives in [`mcp`] and root-confined filesystem
//! materialization in [`fs`], each behind its own feature, so this crate's
//! default build carries no transport, framework, or filesystem dependency.

#[cfg(feature = "fs")]
pub mod fs;
#[cfg(feature = "mcp")]
pub mod mcp;

use std::fmt;
use std::path::{Component, Path, PathBuf};

/// The only blueprint schema understood by the initial authoring slice.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BlueprintVersion {
    /// Initial, intentionally narrow project blueprint.
    V1,
}

/// The kind of crate generated by a project blueprint.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ProjectKind {
    /// A reusable Rust library crate.
    Library,
    /// An executable Rust binary crate.
    Binary,
}

impl ProjectKind {
    /// Returns the conventional source file for this crate kind.
    #[must_use]
    pub const fn source_file(self) -> &'static str {
        match self {
            Self::Library => "src/lib.rs",
            Self::Binary => "src/main.rs",
        }
    }
}

/// A declarative description of one generated Rust workspace.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectBlueprint {
    /// Schema version of this blueprint.
    pub version: BlueprintVersion,
    /// Human-readable workspace name and generated directory name.
    pub workspace_name: String,
    /// Cargo package name for the generated crate.
    pub package_name: String,
    /// Whether to generate a library or binary crate.
    pub kind: ProjectKind,
    /// SPDX license expression recorded in Cargo metadata.
    pub license: String,
    /// Optional package description recorded in Cargo metadata.
    pub description: Option<String>,
}

impl ProjectBlueprint {
    /// Creates a version-one project blueprint.
    #[must_use]
    pub fn v1(
        workspace_name: impl Into<String>,
        package_name: impl Into<String>,
        kind: ProjectKind,
        license: impl Into<String>,
        description: Option<String>,
    ) -> Self {
        Self {
            version: BlueprintVersion::V1,
            workspace_name: workspace_name.into(),
            package_name: package_name.into(),
            kind,
            license: license.into(),
            description,
        }
    }
}

/// Stable validation categories exposed by the authoring core.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ValidationCode {
    /// A required field contains only whitespace.
    EmptyField,
    /// A Cargo-compatible name contains unsupported characters.
    InvalidName,
    /// A description is present but contains only whitespace.
    EmptyDescription,
}

/// The severity assigned to a validation finding.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum FindingSeverity {
    /// The blueprint cannot be planned or generated.
    Error,
    /// The blueprint is valid but can be improved.
    Warning,
}

/// One typed result from blueprint validation.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ValidationFinding {
    /// Machine-readable validation category.
    pub code: ValidationCode,
    /// Whether this finding prevents generation.
    pub severity: FindingSeverity,
    /// Blueprint field associated with the finding.
    pub field: &'static str,
    /// Human-readable explanation suitable for a tool response.
    pub message: String,
}

/// The complete result of validating a blueprint.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct ValidationReport {
    /// Findings in deterministic field order.
    pub findings: Vec<ValidationFinding>,
}

impl ValidationReport {
    /// Returns whether generation may proceed.
    #[must_use]
    pub fn is_valid(&self) -> bool {
        !self
            .findings
            .iter()
            .any(|finding| finding.severity == FindingSeverity::Error)
    }
}

/// A file in a deterministic generation plan.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GeneratedFile {
    relative_path: PathBuf,
    contents: String,
}

impl GeneratedFile {
    fn new(relative_path: impl Into<PathBuf>, contents: impl Into<String>) -> Self {
        Self {
            relative_path: relative_path.into(),
            contents: contents.into(),
        }
    }

    /// Returns the path relative to the generated workspace root.
    #[must_use]
    pub fn relative_path(&self) -> &Path {
        &self.relative_path
    }

    /// Returns the deterministic contents that should be written to the file.
    #[must_use]
    pub fn contents(&self) -> &str {
        &self.contents
    }
}

/// A command users can run to validate a generated workspace.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct QualityCommand {
    /// Executable name.
    pub program: &'static str,
    /// Ordered command arguments.
    pub arguments: Vec<&'static str>,
}

/// A pure, ordered plan for generating a Rust workspace.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GenerationPlan {
    /// Generated files in stable order.
    pub files: Vec<GeneratedFile>,
    /// Standard quality checks supported by the generated workspace.
    pub quality_commands: Vec<QualityCommand>,
}

/// A root-relative destination directory for materialization.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectTarget(String);

impl ProjectTarget {
    /// Creates a one-component target directory name.
    ///
    /// # Errors
    ///
    /// Returns [`TargetError::Invalid`] when the value is empty, absolute, nested, or contains a non-normal path component.
    pub fn new(value: impl Into<String>) -> Result<Self, TargetError> {
        let value = value.into();
        let path = Path::new(&value);
        if value.is_empty()
            || path.is_absolute()
            || path.components().count() != 1
            || !matches!(path.components().next(), Some(Component::Normal(_)))
        {
            return Err(TargetError::Invalid(value));
        }
        Ok(Self(value))
    }

    /// Returns this target as a path relative to an adapter's configured root.
    #[must_use]
    pub fn as_path(&self) -> &Path {
        Path::new(&self.0)
    }

    /// Returns the stable target identifier without exposing an adapter root.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// The outcome of materializing a generation plan.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MaterializedProject {
    /// The root-relative target selected for this project.
    pub target: ProjectTarget,
    /// Paths written relative to the generated project root.
    pub written_files: Vec<PathBuf>,
}

/// A port for materializing an already validated plan.
pub trait ProjectWriter {
    /// Adapter-defined error type.
    type Error;

    /// Safely writes a plan under the adapter's configured root.
    ///
    /// # Errors
    ///
    /// Returns the adapter-defined error when the plan cannot be materialized safely.
    fn write(
        &self,
        plan: &GenerationPlan,
        target: &ProjectTarget,
    ) -> Result<MaterializedProject, Self::Error>;
}

/// The public contract for project authoring.
pub trait ProjectAuthor {
    /// Returns all deterministic findings for a blueprint.
    fn validate(&self, blueprint: &ProjectBlueprint) -> ValidationReport;

    /// Creates a plan only when the blueprint contains no error findings.
    ///
    /// # Errors
    ///
    /// Returns [`AuthoringError::InvalidBlueprint`] when validation reports one or more errors.
    fn plan(&self, blueprint: &ProjectBlueprint) -> Result<GenerationPlan, AuthoringError>;
}

/// The built-in deterministic author for version-one blueprints.
#[derive(Clone, Copy, Debug, Default)]
pub struct DefaultProjectAuthor;

impl ProjectAuthor for DefaultProjectAuthor {
    fn validate(&self, blueprint: &ProjectBlueprint) -> ValidationReport {
        let mut findings = Vec::new();
        validate_name("workspace_name", &blueprint.workspace_name, &mut findings);
        validate_name("package_name", &blueprint.package_name, &mut findings);
        validate_required("license", &blueprint.license, &mut findings);
        if blueprint
            .description
            .as_deref()
            .is_some_and(|description| description.trim().is_empty())
        {
            findings.push(ValidationFinding {
                code: ValidationCode::EmptyDescription,
                severity: FindingSeverity::Warning,
                field: "description",
                message: "description is blank and will be omitted".to_owned(),
            });
        }
        ValidationReport { findings }
    }

    fn plan(&self, blueprint: &ProjectBlueprint) -> Result<GenerationPlan, AuthoringError> {
        let report = self.validate(blueprint);
        if !report.is_valid() {
            return Err(AuthoringError::InvalidBlueprint(report));
        }
        Ok(build_plan(blueprint))
    }
}

/// Errors from the pure authoring core.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum AuthoringError {
    /// A blueprint has one or more error findings.
    InvalidBlueprint(ValidationReport),
}

impl fmt::Display for AuthoringError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidBlueprint(report) => write!(
                formatter,
                "project blueprint has {} validation finding(s)",
                report.findings.len()
            ),
        }
    }
}

impl std::error::Error for AuthoringError {}

/// Errors returned when building a root-relative target name.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum TargetError {
    /// The value was not a single normal relative path component.
    Invalid(String),
}

impl fmt::Display for TargetError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Invalid(value) => write!(formatter, "invalid project target: {value}"),
        }
    }
}

impl std::error::Error for TargetError {}

fn validate_name(field: &'static str, value: &str, findings: &mut Vec<ValidationFinding>) {
    if value.trim().is_empty() {
        findings.push(ValidationFinding {
            code: ValidationCode::EmptyField,
            severity: FindingSeverity::Error,
            field,
            message: format!("{field} must not be empty"),
        });
    } else if !is_cargo_name(value) {
        findings.push(ValidationFinding {
            code: ValidationCode::InvalidName,
            severity: FindingSeverity::Error,
            field,
            message: format!("{field} must use ASCII letters, digits, '-' or '_', and start with a letter or digit"),
        });
    }
}

fn validate_required(field: &'static str, value: &str, findings: &mut Vec<ValidationFinding>) {
    if value.trim().is_empty() {
        findings.push(ValidationFinding {
            code: ValidationCode::EmptyField,
            severity: FindingSeverity::Error,
            field,
            message: format!("{field} must not be empty"),
        });
    }
}

fn is_cargo_name(value: &str) -> bool {
    let mut characters = value.bytes();
    matches!(characters.next(), Some(byte) if byte.is_ascii_alphanumeric())
        && characters.all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_'))
}

fn build_plan(blueprint: &ProjectBlueprint) -> GenerationPlan {
    let package_path = format!("crates/{}", blueprint.package_name);
    let source_path = format!("{package_path}/{}", blueprint.kind.source_file());
    let description = blueprint
        .description
        .as_deref()
        .filter(|description| !description.trim().is_empty())
        .map(|description| format!("description = {description:?}\n"))
        .unwrap_or_default();
    let root_manifest = format!(
        "[workspace]\nmembers = [\"{package_path}\"]\nresolver = \"3\"\n\n[workspace.package]\nversion = \"0.1.0\"\nedition = \"2024\"\nlicense = {license:?}\nrust-version = \"1.88\"\n{description}\n[workspace.lints.rust]\nunsafe_code = \"forbid\"\nrust_2018_idioms = {{ level = \"deny\", priority = -1 }}\n\n[workspace.lints.clippy]\nall = {{ level = \"warn\", priority = -1 }}\npedantic = {{ level = \"warn\", priority = -1 }}\n",
        license = blueprint.license,
    );
    let crate_manifest = format!(
        "[package]\nname = {name:?}\nversion.workspace = true\nedition.workspace = true\nlicense.workspace = true\nrust-version.workspace = true\n\n[lints]\nworkspace = true\n",
        name = blueprint.package_name,
    );
    let source = match blueprint.kind {
        ProjectKind::Library => "//! Generated by Rust Factory.\n".to_owned(),
        ProjectKind::Binary => {
            "fn main() {\n    println!(\"Hello from Rust Factory.\");\n}\n".to_owned()
        }
    };
    let readme = format!(
        "# {}\n\nGenerated by Rust Factory.\n",
        blueprint.workspace_name
    );
    GenerationPlan {
        files: vec![
            GeneratedFile::new(".gitignore", "/target\n"),
            GeneratedFile::new("Cargo.toml", root_manifest),
            GeneratedFile::new(
                "Makefile",
                ".PHONY: fmt fmt-check lint test check\n\nfmt:\n\tcargo fmt --all\n\nfmt-check:\n\tcargo fmt --all -- --check\n\nlint:\n\tcargo clippy --workspace --all-targets -- -D warnings\n\ntest:\n\tcargo test --workspace\n\ncheck: fmt-check lint test\n",
            ),
            GeneratedFile::new("README.md", readme),
            GeneratedFile::new(format!("{package_path}/Cargo.toml"), crate_manifest),
            GeneratedFile::new(source_path, source),
        ],
        quality_commands: vec![QualityCommand {
            program: "make",
            arguments: vec!["check"],
        }],
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn valid_blueprint(kind: ProjectKind) -> ProjectBlueprint {
        ProjectBlueprint::v1(
            "example-workspace",
            "example_crate",
            kind,
            "Apache-2.0",
            Some("An example generated workspace.".to_owned()),
        )
    }

    #[test]
    fn plans_are_deterministic() {
        let author = DefaultProjectAuthor;
        let blueprint = valid_blueprint(ProjectKind::Library);
        assert_eq!(author.plan(&blueprint), author.plan(&blueprint));
    }

    #[test]
    fn invalid_names_prevent_planning() {
        let author = DefaultProjectAuthor;
        let blueprint =
            ProjectBlueprint::v1("bad name", "crate", ProjectKind::Library, "MIT", None);
        let report = author.validate(&blueprint);
        assert!(!report.is_valid());
        assert_eq!(report.findings[0].code, ValidationCode::InvalidName);
        assert!(matches!(
            author.plan(&blueprint),
            Err(AuthoringError::InvalidBlueprint(_))
        ));
    }

    #[test]
    fn binary_plan_uses_main_source_file() {
        let plan = DefaultProjectAuthor
            .plan(&valid_blueprint(ProjectKind::Binary))
            .expect("valid blueprint should plan");
        assert!(
            plan.files
                .iter()
                .any(|file| file.relative_path() == Path::new("crates/example_crate/src/main.rs"))
        );
    }

    #[test]
    fn targets_are_single_normal_components() {
        assert!(ProjectTarget::new("safe-project").is_ok());
        assert!(ProjectTarget::new("../outside").is_err());
        assert!(ProjectTarget::new("nested/project").is_err());
    }
}
